import { IShop } from "./IShop";

export interface IBountiesItem {
  activation_description: string;
  amount: number | null;
  availability: number;
  consume_points: boolean;
  cr_points: number | null;
  cr_rank: number;
  description: string | null;
  highscore_contest: boolean;
  id: string;
  image: string;
  is_activateable: boolean | null;
  is_activated: boolean | null;
  is_active: boolean;
  throttle: number | null;
  time_range_redeem_count: number | null;
  contest: boolean;
  is_redeemable: boolean | null;
  limited: boolean;
  name: string;
  needed_points: number;
  needed_visits: number;
  pictures: Array<string>;
  point_contest: boolean;
  ranks: number;
  redeem_count: number | null;
  redeem_description: string;
  require_shop_when_redeemed: boolean;
  show_progress_bar: boolean;
  single_use: boolean;
  shipping: boolean;
  redeem_success_alert_text: string;
  app_form: Partial<any> | null;
  bounty_redeem_alert_header: string;
  bounty_redeem_alert_text: string;
  show_ranking: boolean;
  contest_type: string | null;
  can_participate: boolean | null;
  is_participating: boolean | null;
  required_status: number | null;
  instant: boolean;
  valid_from: Partial<any> | null;
  valid_until: string | null;
  manual_claim: boolean;
  shop: IShop;
  category: string | null;
  condition_id: string | null;
  is_expired: boolean;
  point_pool: string | null;
  order: string | null;
  terms: string | null;
  variations: string | null;
  type: number;
  reward_is_collected?: boolean;
}
